= Starflight - The Lost Colony

== Welcome

Starflight - The Lost Colony is a sci-fi adventure game for a single player with space exploration, character development, alien races to encounter, and an engrossing storyline that unfolds as the player gradually explores the galaxy. The Lost Colony is based on two previous games from Electronic Arts: __Starflight__ (1986) and the sequel, __Starflight II: Trade Routes of the Cloud Nebula__ (1988). Starflight features free-roaming gameplay that spans hundreds of star systems and numerous alien races. A compelling storyline pits the player against a vast enemy endangering all life in the galaxy.  Hundreds of unique planetary systems filled with planets and asteroids that can be landed on and explored in real time. Players will interact with lifeforms (some hostile!) and mine minerals in order to raise capital for ship upgrades and fuel.

Choose from among three professions (Military, Science, Freelance). Upgrade your ship with new technology. Hire and train a crew. Encounter alien races–and when diplomacy fails, engage in real-time capital ship combat.  The combat simulation takes place in real time, with some realism and arcade-style fun combined for a balanced gameplay. Powerups and debris from destroyed alien ships can be picked up by the player.

A series of training missions first introduces the player to the story that unfolds as the player completes missions and interacts with alien cultures.  A complex quest system then takes the player into the home system to explore planets, and then out into deep space to explore other star systems and meet and interact with other alien races. As the plot develops multiple progressive galaxy wide shifts take place changing the dialogue and interactions with alien races on a fundamental level.

Continues the gameplay tradition of the original games in the series: Starflight and Starflight II : Trade Routes of the Cloud Nebula. The original gameplay has been largely preserved with modifications to meet the expectations of modern gamers. The Lost Colony takes place in parallel with the original Starflight time period, but in a different part of the galaxy. See the Opening Story for historical perspective and tie-in.

This project was developed over a period of several years in C++ with Allegro 4.2. It was intended to be released as freeware from the beginning (with approval from original Starflight creator, Rod McConnell). Early design work began in late 2006 with a small group of fans who developed early prototypes and concepts for about a year in their spare time. In late 2007, a group of UAT students gave the game a boost as an internship project and demonstrated it at GDC in early 2008, but it still had a long ways to go! By late 2008, script code brought the plot to life with more realistic alien encounters and a new quest system was added. In 2009, the engine and scripts were mostly finished and the game was submitted to IGF (but was not chosen as a finalist). By mid 2010, the last beta was released.
