#ifndef DEBUG_H
#define DEBUG_H
// The debugging keys are activated by defining the DEBUG_KEYS in
// the compiler's #def options.

// ALLEGRO_KEY_PAD_PLUS, ALLEGRO_KEY_PAD_MINUS
#define STARPORT_QUEST_PLUS ALLEGRO_KEY_F9
#define STARPORT_QUEST_MINUS ALLEGRO_KEY_F8
#define STARPORT_ADD_CREDITS ALLEGRO_KEY_F10

// Interstellar travel module:		ALLEGRO_KEY_PAD_N/ALLEGRO_KEY_FN
#define FORCE_ENCOUNTER_PIRATE ALLEGRO_KEY_F1
#define FORCE_ENCOUNTER_ELOWAN ALLEGRO_KEY_F2
#define FORCE_ENCOUNTER_SPEMIN ALLEGRO_KEY_F3
#define FORCE_ENCOUNTER_THRYNN ALLEGRO_KEY_F4
#define FORCE_ENCOUNTER_BARZHON ALLEGRO_KEY_F5
#define FORCE_ENCOUNTER_NYSSIAN ALLEGRO_KEY_F6
#define FORCE_ENCOUNTER_TAFEL ALLEGRO_KEY_F7
#define FORCE_ENCOUNTER_MINEX ALLEGRO_KEY_F8
#define FORCE_ENCOUNTER_COALITION ALLEGRO_KEY_F9

#define IST_QUEST_PLUS ALLEGRO_KEY_F11
#define IST_QUEST_MINUS ALLEGRO_KEY_F12

#define IST_STAGE_PLUS ALLEGRO_KEY_PAD_PLUS
#define IST_STAGE_MINUS ALLEGRO_KEY_PAD_MINUS

// Encounter module: alien attitudes adjust -/+:
#define ALIEN_ATTITUDE_MINUS ALLEGRO_KEY_F8
#define ALIEN_ATTITUDE_PLUS ALLEGRO_KEY_F9

#define ENC_QUEST_PLUS ALLEGRO_KEY_F11
#define ENC_QUEST_MINUS ALLEGRO_KEY_F12

#endif
