name: Windows build
on: [workflow_dispatch]
jobs:
  Win64:
    runs-on: windows-2019
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v2
      - uses: msys2/setup-msys2@v2
        with:
          install: >-
            make
            mingw-w64-x86_64-cmake
            mingw-w64-x86_64-clang
            mingw-w64-x86_64-pkgconf
            mingw-w64-x86_64-allegro
            mingw-w64-x86_64-dumb
            mingw-w64-x86_64-flac
            mingw-w64-x86_64-opusfile
            mingw-w64-x86_64-freetype
            mingw-w64-x86_64-libjpeg-turbo
            mingw-w64-x86_64-libpng
            mingw-w64-x86_64-libvorbis
            mingw-w64-x86_64-libwebp
            mingw-w64-x86_64-openal
            mingw-w64-x86_64-physfs
            mingw-w64-x86_64-yaml-cpp
            mingw-w64-x86_64-nsis
            mingw-w64-x86_64-lua
      - name: CMake
        env:
          PATH: /mingw64/bin:$PATH
        run: mkdir build; cd build; cmake -DBUILD_SHARED_LIBS=off -G "MSYS Makefiles" ..
      - name: make
        env:
          PATH: /mingw64/bin:$PATH
        run: cd build; make
      - name: Package
        env:
          PATH: /mingw64/bin:$PATH
        run: cd build ; cpack -G "NSIS" ..
      - uses: actions/upload-artifact@v3
        with:
          name: build
          path: "build/*.exe"
      - uses: actions/upload-artifact@v3
        name: upload build logs
        if: always()
        with:
          name: build-logs
          path: "build/*/*.log"
